name: Test Spac
on:
  pull_request:
  push:
    branches:
      - master
      - "*"
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        ros_distribution: # Only include ROS 2 distributions, as ROS 1 does not support macOS and Windows.
          - humble
          - iron
          - rolling
      fail-fast: false
    steps:
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@v0.6
      with:
        use-ros2-testing: true
        required-ros-distributions: ${{ matrix.ros_distribution }}
    - name: Run Tests
      uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: spac
    - name: Upload Logs-
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()